# Generated by Django 4.2.7 on 2023-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('type_of_doctor', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=300)),
                ('experience', models.FloatField(default=0.0)),
                ('review', models.FloatField(default=0.0)),
                ('medical_registration', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=300)),
                ('availability_dates_start', models.DateField(default='2023-01-01')),
                ('availability_dates_end', models.DateField(default='2023-01-01')),
                ('availability_times', models.TimeField(default='09:00:00')),
                ('availability_times_end', models.TimeField(default='17:00:00')),
                ('price', models.FloatField(default=100.0)),
                ('address_clinic', models.CharField(max_length=400)),
            ],
        ),
    ]
